spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://allinone.cn5daduvgses.us-east-1.rds.amazonaws.com:3306/allinonedb
    username: admin
    password: Admin1234
    hikari:
      auto-commit: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: todolistorganization@gmail.com
    password: rgankytzymfbyphy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

parse:
  turbo-az:
    cron: 0 0/2 * * * *
    enable-schedule: true

server:
  port: 5000