spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://allinonedb.cogkt6vcjbtv.us-east-2.rds.amazonaws.com:3306/allinonedb
    username: admin
    password: AllInOne12345
    hikari:
      auto-commit: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: todolistorganization@gmail.com
    password: rgankytzymfbyphy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 4545