spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://allinonedb.cogkt6vcjbtv.us-east-2.rds.amazonaws.com:3306/allinonedb
    username: admin
    password: AllInOne12345
    hikari:
      auto-commit: false
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: todolistorganization@gmail.com
    password: rgankytzymfbyphy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

hibernate:
  dialect:
    storage_engine: innodb

server:
  port: 4545