package com.all.in.one.allinone.model.enums.turboAzEnums;

import lombok.Getter;

import java.util.Arrays;

@Getter
public enum Brand {

    ABARTH("Abarth", 280),
    ABM("ABM", 232),
    ACG_CARS("ACG Cars", 250),
    ACURA("Acura", 28),
    ALFA_ROMEO("Alfa Romeo", 30),
    ALKE("Alke", 254),
    AMC("AMC", 267),
    APRILIA("Aprilia", 156),
    ARCTIC_CAT("Arctic Cat", 249),
    ARGO("Argo", 273),
    ARO("ARO", 262),
    ARORA("Arora", 178),
    ASHOK_LEYLAND("Ashok Leyland", 221),
    ASIA("Asia", 134),
    ASTON_MARTIN("Aston Martin", 86),
    ATV("ATV", 268),
    AUDI("Audi", 9),
    AVIA("Avia", 274),
    BAIC("Baic", 218),
    BAJAJ("Bajaj", 327),
    BAOTIAN("Baotian", 174),
    BAW("BAW", 226),
    BAZ("BAZ", 330),
    BELKA("Belka", 215),
    BENELLI("Benelli", 375),
    BENTLEY("Bentley", 19),
    BESTUNE("Bestune", 387),
    BMC("BMC", 136),
    BMW("BMW", 3),
    BMW_ALPINA("BMW Alpina", 62),
    BRILLIANCE("Brilliance", 92),
    BUELL("Buell", 228),
    BUGATTI("Bugatti", 408),
    BUICK("Buick", 84),
    BULL_MOTORS("Bull Motors", 378),
    BYD("BYD", 51),
C_MOTO("C.Moto", 395),
    CADILLAC("Cadillac", 38),
    CAN_AM("Can-Am", 220),
    CELIMO("Celimo", 153),
    CEVO("Cevo", 397),
    CFMOTO("CFMOTO", 259),
    CHANGAN("Changan", 163),
    CHERY("Chery", 52),
    CHEVROLET("Chevrolet", 41),
    CHITUMA("Chituma", 225),
    CHRYSLER("Chrysler", 10),
    CITROEN("Citroen", 27),
    CNG_BUS("CNG Bus", 107),
    COLES("Coles", 177),
    CZ("CZ", 239),
    DACIA("Dacia", 76),
    DADI("Dadi", 180),
    DAEWOO("Daewoo", 11),
    DAF("DAF", 91),
    DAIHATSU("Daihatsu", 66),
    DALI("Dali", 173),
    DATSUN("Datsun", 270),
    DAYUN("Dayun", 148),
    DERWAYS("Derways", 279),
    DFSK("DFSK", 405),
    DNEPR("Dnepr", 162),
    DODGE("Dodge", 60),
    DONGFENG("DongFeng", 117),
    DUCATI("Ducati", 147),
    ENTEGRA_COACH("Entegra Coach", 372),
    ERAZ("ErAZ", 266),
    ERF("ERF", 176),
    ESTRIMA("Estrima", 256),
    EUROTEX("Eurotex", 241),
    FAUN("FAUN", 244),
    FAW("FAW", 79),
    FERRARI("Ferrari", 42),
    FIAT("Fiat", 37),
    FODAY("Foday", 278),
    FORD("Ford", 2),
    FOTON("Foton", 49),
    FREIGHTLINER("Freightliner", 275),
    FSO("FSO", 401),
    GABRO("Gabro", 159),
    GAC("GAC", 175),
    GAZ("GAZ", 21),
    GEELY("Geely", 72),
    GEM_CARS("GEM Cars", 248),
    GENESIS("Genesis", 376),
    GEON("Geon", 182),
    GIBBS("GIBBS", 263),
    GILERA("Gilera", 151),
    GINAF("Ginaf", 137),
    GMC("GMC", 82),
    GONOW("Gonow", 58),
    GREAT_WALL("Great Wall", 50),
    HAFEI("Hafei", 65),
    HAIMA("Haima", 383),
    HAMTAZ("Hamtaz", 154),
    HAOJUE("Haojue", 142),
    HARLEY_DAVIDSON("Harley-Davidson", 140),
    HAVAL("Haval", 242),
    HISUN("Hisun", 258),
    HONDA("Honda", 12),
    HONGQI("Hongqi", 388),
    HOWO("HOWO", 110),
    HOZON("Hozon", 409),
    HUMMER("Hummer", 13),
    HUZHOU("Huzhou", 240),
    HYOSUNG("Hyosung", 167),
    HYUNDAI("Hyundai", 1),
    IFA("IFA", 166),
    IJ("IJ", 64),
    IKARUS("Ikarus", 101),
    INFINITI("Infiniti", 15),
    IRAN_KHODRO("Iran Khodro", 116),
    IRBIS("Irbis", 276),
    ISUZU("Isuzu", 74),
    ITALCAR("ItalCar", 253),
    IVANOVEC("Ivanovec", 224),
    IVECO("Iveco", 67),
    JAC("JAC", 124),
    JAGUAR("Jaguar", 35),
    JAWA("Jawa", 155),
    JEEP("Jeep", 36),
    JETOUR("Jetour", 384),
    JIAJUE("Jiajue", 216),
    JIANSHE("Jianshe", 337),
    JINAN("Jinan", 265),
    JINBEI("Jinbei", 168),
    JMC("JMC", 109),
    JONWAY("Jonway", 235),
    KAIYI("KAIYI", 390),
    KAMAZ("KamAz", 90),
    KANUNI("Kanuni", 406),
    KARSAN("Karsan", 407),
    KAVZ("KAvZ", 88),
    KAWASAKI("Kawasaki", 139),
    KAYO("Kayo", 374),
    KAZ("KAZ", 237),
    KEEWAY("Keeway", 338),
    KHAZAR("Khazar", 282),
    KIA("Kia", 8),
    KINROAD("Kinroad", 169),
    KRAZ("KrAZ", 119),
    KTM("KTM", 141),
    KUBA("Kuba", 332),
    LADA_VAZ("LADA (VAZ)", 5),
    LAMBORGHINI("Lamborghini", 43),
    LANCIA("Lancia", 69),
    LAND_ROVER("Land Rover", 20),
    LAZ("LAZ", 179),
    LEXUS("Lexus", 14),
    LIEBHERR("Liebherr", 102),
    LIFAN("Lifan", 87),
    LINCOLN("Lincoln", 46),
    LOTUS("Lotus", 238),
    LUAZ("LuAz", 103),
    LVTONG("Lvtong", 391),
    MACK("Mack", 329),
    MAGIRUS_DEUTZ("Magirus-Deutz", 382),
    MAN("MAN", 112),
    MARSHELL("Marshell", 257),
    MASERATI("Maserati", 44),
    MAYBACH("Maybach", 129),
    MAZ("MAZ", 100),
    MAZDA("Mazda", 26),
    MCLAREN("McLaren", 326),
    MEGELLI("Megelli", 172),
    MERCEDES("Mercedes", 4),
    MERCEDES_MAYBACH("Mercedes-Maybach", 252),
    MERCURY("Mercury", 47),
    MG("MG", 127),
    MINI("Mini", 31),
    MINSK("Minsk", 146),
    MITSUBISHI("Mitsubishi", 6),
    MONDIAL("Mondial", 286),
    MOSKVICH("Moskvich", 81),
    MURAVEY("Muravey", 243),
    MV_AGUSTA("MV Agusta", 158),
    NAMA("Nama", 324),
    NEMAN("Neman", 283),
    NEOPLAN("Neoplan", 227),
    NEPTUN("Neptun", 161),
    NISSAN("Nissan", 7),
    NIU("NIU", 379),
    NOOMA("Nooma", 371),
    OLDSMOBILE("Oldsmobile", 106),
    OLTCIT("Oltcit", 394),
    OPEL("Opel", 29),
    OTOCAR("Otocar", 181),
    OTOSAN("Otosan", 269),
    PACKARD("Packard", 271),
    PARVAZ("Parvaz", 222),
    PAYKAN("Paykan", 246),
    PAZ("PAZ", 114),
    PEUGEOT("Peugeot", 16),
    PIAGGIO("Piaggio", 152),
    PILOTCAR("Pilotcar", 392),
    PLYMOUTH("Plymouth", 126),
    POLARIS("Polaris", 247),
    POLESTAR("Polestar", 396),
    PONTIAC("Pontiac", 48),
    PORSCHE("Porsche", 32),
    PROTON("Proton", 135),
    RAF("RAF", 105),
    RAVON("Ravon", 272),
    RENAULT("Renault", 17),
    RIALLI("Rialli", 284),
    RIEJU("Rieju", 234),
    RIGA("Riga", 229),
    RKS("RKS", 333),
    ROEWE("Roewe", 171),
    ROLLS_ROYCE("Rolls-Royce", 18),
    ROVER("Rover", 78),
    SAAB("Saab", 80),
    SAIPA("Saipa", 94),
    SAMAUTO("SamAuto", 377),
    SATURN("Saturn", 93),
    SCANIA("Scania", 108),
    SCION("Scion", 251),
    SEAT("SEAT", 59),
    SEAZ("SeAz", 97),
    SETRA("Setra", 115),
    SHACMAN("Shacman", 133),
    SHAOLIN("Shaolin", 132),
    SHINERAY("Shineray", 144),
    SHUANGHUAN("Shuanghuan", 288),
    SINOTECH("Sinotech", 400),
    SKODA("Skoda", 22),
    SKYLINE("Skyline", 160),
    SKYWELL("Skywell", 399),
    SMART("Smart", 61),
    SMZ("SMZ", 322),
    SOUEAST("Soueast", 402),
    SPORT("Sport", 264),
    SSANG_YONG("Ssang Yong", 45),
    STAR("Star", 393),
    SUBARU("Subaru", 34),
    SUZUKI("Suzuki", 33),
    SYM("SYM", 380),
    TALBOT("Talbot", 334),
    TATA("Tata", 231),
    TATRA("Tatra", 98),
    TAZZARI("Tazzari", 255),
    TEMSA("Temsa", 128),
    TESLA("Tesla", 245),
    TOFAS("Tofas", 39),
    TOYOTA("Toyota", 23),
    TRABANT("Trabant", 236),
    TRIUMPH("Triumph", 233),
    TUFAN("Tufan", 385),
    UAZ("UAZ", 53),
    URAL("Ural", 145),
    VELOCI("Veloci", 170),
    VESPA("Vespa", 223),
    VOLKSWAGEN("Volkswagen", 24),
    VOLTA("Volta", 386),
    VOLVO("Volvo", 25),
    VOSXOD("Vosxod", 150),
    VYATKA("Vyatka", 149),
    WAITZINGER("Waitzinger", 165),
    WANFENG("Wanfeng", 335),
    WILD_WEST("Wild West", 389),
    WILLYS("Willys", 77),
    WULING("Wuling", 404),
    XCMG("XCMG", 219),
    XIN_KAI("Xin Kai", 157),
    XINLING("Xinling", 373),
    YADEA("Yadea", 381),
    YAMAHA("Yamaha", 138),
    YUEJIN("Yuejin", 325),
    YUFENG("Yufeng", 281),
    YUTONG("Yutong", 331),
    ZAMYAD("Zamyad", 328),
    ZAZ("ZAZ", 57),
    ZEEKR("Zeekr", 403),
    ZIL("ZIL", 85),
    ZONGSHEN("Zongshen", 285),
    ZONTES("Zontes", 143),
    ZOOMLION("Zoomlion", 164),
    ZUK("Zuk", 398),
    ZX_AUTO("ZX Auto", 217);

    private final String value;
    private final int id;

    Brand(String value, int id) {
        this.value = value;
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public int getId() {
        return id;
    }

    public static Brand getBrand(String value) {
        return Arrays.stream(Brand.values())
                .filter(b -> b.getValue().equals(value))
                .findFirst()
                .orElse(null);
    }

}
